name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "SAO Infinity"
  comment: "SAO"
  url: "https://static.emulatorgames.net/static2/roms/playstation-portable/Sword%20Art%20Online%20-%20Infinity%20Moment%20(Japan).7z"
  file_name: "SAO Infinity Moment.7z"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
